version: "3.8"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile

    deploy:
      mode: global
      restart_policy:
        condition: any

    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

    networks:
      - global

networks:
  global:
    external: true